- name: Install apt packages
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
    - php5-fpm
  become: true

- name: Copy php-fpm conf file
  copy: src=www.conf dest=/etc/php5/fpm/pool.d/www.conf
  become: true
  notify: Restart php5-fpm
